### ISSUE TITLE
install.sh fails on MacOS Mojave 

### ISSUE THREAD

**Issue by alfred-bratterud** [includeos/IncludeOS#1950]
At least on my system I'm getting `stdio.h` file not found. I've only tried the dev branch.

**Comment by AndreasAakesson** [comment]
I got the same after upgrade but with `string.h`.
Found a solution [here](https://stackoverflow.com/a/52530212/1842128):
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`
