### ISSUE TITLE
Failure to build - Ubuntu16.04 and clang-7

### ISSUE THREAD

**Issue by wilsonk** [includeos/IncludeOS#2053]
I had a strange issue with the install.sh script not recognizing my manually installed (all default options) ```clang-7``` compiler. It seems as though the ```install_dependencies_linux.sh``` script expects a clang major and minor version (ie. 3 characters like '7.0') and it gets tripped up with the default, manually installed ```clang-7``` because the binary is called ```/usr/local/bin/clang-7``` with only the major version enumerated.

I fixed this by simply symlinking from ```/usr/local/bin/clang-7.0```and ```/usr/local/bin/clang++-7.0``` to the ```clang-7``` binary...and then setting the CC and CXX env variables to point to the '7.0' versions. Perhaps there should be a note about this in the README or the script should be more robust? I only mention this as fixing this with the symlinks is slightly unintuitive and may be rather frustrating to figure out :)

**Comment by ingve** [comment]
Hi @wilsonk! Thanks for letting us know about this. Very good that you were able to find a workaround. :+1:

The `install.sh` script and its utility scripts could certainly be more robust. @KristianJerpetjon is working on using Conan for a lot of the setup and installation tasks, so hopefully the whole `install.sh` procedure should be radically simplified soon, but feel free to create a PR (towards the `dev` branch) with suggested wording for the README in the meantime.

**Comment by fwsGonzo** [comment]
Does the manual_build.sh script work for you?

**Comment by wilsonk** [comment]
The manual_build.sh script does work as long as you set CC=/usr/local/bin/clang-7 and CXX=/usr/local/bin/clang++ (this assumes that clang++ points to clang-7).
