### ISSUE TITLE
How to write data to a file?

### ISSUE THREAD

**Issue by LewisTian** [includeos/IncludeOS#2111]
I tried to write something to a file, but I failed. Could you please help me?
```
// Unable to open file!
ofstream f ("test.txt");
if (f.is_open()) {
    f << "File test...\n";
    f.close();
}
else {
    cout << "Unable to open file!\n";
}
```
Thanks in advance.

**Comment by fwsGonzo** [comment]
There is no writable filesystem right now, but we have done some work on writing blocks to disks. So if you need permanent storage you can at least write your down directly as blocks to a disk.

**Comment by LewisTian** [comment]
Thanks for your reply!:smile:
Is there any demo about writing blocks to disks?
