### ISSUE TITLE
stop option enable shutting down now

### ISSUE THREAD

**Issue by Kiritimati** [includeos/IncludeOS#2127]
After finished the installing, I run the test.sh.But after building successfully, the service did not start running.
![图片](https://user-images.githubusercontent.com/24604028/55670123-11a61c80-58b3-11e9-9766-b843f862f617.png)
What should I do?

**Comment by MagnusS** [comment]
We now check for availability of RDRAND and RDSEED instructions and terminate if they are not available. Which platform are you using? The boot script should have handled this for you, so this may be a bug.

**Comment by Kiritimati** [comment]
Thanks for your replying.
I run ubuntu18.04 on vmware workstation 14 and installed the IncludeOS successfully.

**Comment by Kiritimati** [comment]
My classmate installed the IncludeOS14.0 and run test.sh successfully.

**Comment by MagnusS** [comment]
Hm, if you have rdrand or rdseed you should see it in `/proc/cpuinfo`. What's the output of `cat /proc/cpuinfo | grep flags` inside the ubuntu VM?

**Comment by alfred-bratterud** [comment]
There's an option to disable this feature here:
https://github.com/includeos/IncludeOS/blob/master/cmake/post.service.cmake#L297

**Comment by MagnusS** [comment]
If you enable nested virtualisation for the VM in vmware and pass inn `-cpu kvm64,+rdrand,+rdseed` as a parameter to `qemu` we were able to make it work in VMware fusion. This is not a great solution though, it may be easier to just disable this feature using @alfred-bratterud's suggestion above until we can make this easier.

**Comment by Kiritimati** [comment]
Thanks for your help. I've solved the problem through @alfred-bratterud 's suggestion.

**Comment by hklabbers** [comment]
> Hm, if you have rdrand or rdseed you should see it in `/proc/cpuinfo`. What's the output of `cat /proc/cpuinfo | grep flags` inside the ubuntu VM?

ubuntu 18.04 reports the following for cpuinfo:
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt flush_l1d

**Comment by ezhu5121** [comment]
@alfred-bratterud looks the link is down. could you please repost a valid one?
Thanks!

**Comment by AndreasAakesson** [comment]
Yeah master got updated yesterday - it's now here: https://github.com/includeos/IncludeOS/blob/master/cmake/os.cmake#L112

The CMake option is named `FOR_PRODUCTION`. So what you want to do is either call cmake with that: `cmake <path> -DFOR_PRODUCTION=OFF`, or use `ccmake <path>` to turn it off from there.
