### ISSUE TITLE
WARNING: Environment unsafe for production.

### ISSUE THREAD

**Issue by JuliaRS** [includeos/IncludeOS#2146]
![image](https://user-images.githubusercontent.com/20324416/56800163-0f384200-6823-11e9-98ce-7017a29097ea.png)

When i run ./test.sh, i get WARNING. Why?

**Comment by ingve** [comment]
Thank you for trying IncludeOS! 

This will be documented better in the next release (coming soon!).

There is a related issue at https://github.com/includeos/IncludeOS/issues/2127 which has instructions on how to disable the Stop option:

https://github.com/includeos/IncludeOS/issues/2127#issuecomment-480819029
