### ISSUE TITLE
Router receive the packet itself broadcast and keep sending again

### ISSUE THREAD

**Issue by ggbbr** [includeos/IncludeOS#2151]
I used the example project router to transfer one packet from 10.0.0.0/255.255.255.0 to 10.39.0.0/255.255.255.0. The router transferred the packet from one gateway to another  successfully, but when the other gateway tried to ship it away, it received the packet it send away and tried to send it again. This makes the gateway keeps receiving and sending the same packet again and again.
  I think there is a BUG in the link layer for checking the MAC address, but I dont konw how to fix it. The results are as bellow:
![image](https://user-images.githubusercontent.com/27666755/56911220-0378a400-6adf-11e9-939a-a42d63902085.png)
What should I do?

**Comment by ggbbr** [comment]
actually I have the route(gateway) and packet here, how can I get their MAC address and make a compare?
![image](https://user-images.githubusercontent.com/27666755/56937133-af48e080-6b2d-11e9-86a8-bf4332efb4dc.png)
What function can I use?

**Comment by AndreasAakesson** [comment]
Hi. It looks like you're using the `net/integration/router` as a base, correct? I would say this code is only good for that test alone. We do have a router facility that's much better suited for this, and more tested/used: https://github.com/includeos/IncludeOS/tree/master/examples/router (the routes are setup in config.json).
If you curious about how the forwarding works, it's at the bottom of this header: https://github.com/includeos/IncludeOS/blob/master/api/net/router.hpp

To answer your second question:
To get the interface's MAC addr you can just say `stack.link_addr()`.
To get the MAC addr of the packet, we need to make some hacky stuff... ;) 

The packet on the way up the stack gets "promoted" from Ethernet (link) to IP4 (network) by having its pointer to the payload moved beyond the Ethernet frame and up to the IP4 header. So what we could do is the get the start of the IP4 header and subtract the size of the Ethernet header to find out where it starts (this assumes Ethernet with no VLAN tag).

Hopefully this will work (haven't tried it):
```
#include <net/ethernet/header.hpp>

auto* hdr_ptr = reinterpret_cast<char*>(&pckt->ip_header());
hdr_ptr -= sizeof(net::ethernet::Header);
const auto& eth_hdr = *reinterpret_cast<net::ethernet::Header*>(hdr_ptr);
printf("src=%s dst=%s\n", 
  eth_hdr.src().to_string().c_str(), 
  eth_hdr.dest().to_string().c_str());
```

**Comment by ggbbr** [comment]
Thanks for replying. I am using net/integration/router as a base and it going on pretty good, I used it to link my Linux and another Unikernel Web service. The Linux requests the web from the Web service through the Router Unikernel. It works, just exists the small BUG. About the way to get the MAC address of the Packet seems exists some problem:
![image](https://user-images.githubusercontent.com/27666755/57126960-6a3cdc80-6dc1-11e9-905d-32c81b383ad1.png)
What should I do? Thanks for replying again, your tips are very useful and considerate.

**Comment by AndreasAakesson** [comment]
Ok I see we can simplify it a bit. Try changing first line to:
`auto* hdr_ptr = pckt->layer_begin();`

**Comment by AndreasAakesson** [comment]
@ggbbr Did this solve your problems? Can we close this issue?

**Comment by ggbbr** [comment]
Yes, my problem solved, sorry I am doing the test these days and forgot to reply. Thank you guys so much for your hard-working in this field and your kindness, I benefit from this a lot.
