### ISSUE TITLE
Unsupported compiler target: i686-linux-gnu

### ISSUE THREAD

**Issue by JuliaRS** [includeos/IncludeOS#2154]
![image](https://user-images.githubusercontent.com/20324416/56959842-89d0cc80-6b57-11e9-9138-bd68b868a3d6.png)
I use Ubuntu 14.04.6 i386. How i may install successfully IncludeOS?

**Comment by staiyeba** [comment]
Hi JuliaRS,

We no longer support ubuntu14.04 i386.
Also we are moving away from the `install.sh` script.
If you checkout to our dev branch, you will see we are using conan package manager to build includeos. On the dev branch, you can try building for architecture `i386` with the `x86` conan profiles.

If you run into any issues, feel free to ask for help on our slack channel.

**Comment by JuliaRS** [comment]
Hi, staiyeba,
my laptop is support only 32bit OS, which one can i use then?

**Comment by staiyeba** [comment]
Follow the getting started README on the dev branch here: https://github.com/includeos/IncludeOS/tree/dev

You can try using the `x86` profiles we have defined here: https://github.com/includeos/conan_config/tree/master/profiles

Note that you no longer need to install includeos to run services. i would suggest you try out the hello_world example as described in the readme.

If you give us more details on what you are trying to do with IncludeOS, one of our developers can help you :)

Here is a link to our slack channel if you are interested : https://goo.gl/NXBVsc
