### ISSUE TITLE
Does includeOS support MPI?

### ISSUE THREAD

**Issue by jansende** [includeos/IncludeOS#2163]
Hi,
I would be interested in running MPI applications using includeOS. Is there any support right now? If not, is it planned in the future?

**Comment by fwsGonzo** [comment]
I actually started on MQTT stuff, but I dont know when, if ever, it will be done

**Comment by jansende** [comment]
I think we are talking about different things here. I mean the Message Passing Interface... There is an open implementation for linux, but I have no idea if it is portable.

**Comment by jansende** [comment]
Please reopen. The question has not been answered in any way.
