### ISSUE TITLE
Fresh install, missing prebuild packages for http-parser

### ISSUE THREAD

**Issue by hamfirst** [includeos/IncludeOS#2171]
http-parser/2.8.1@includeos/stable: WARN: Can't find a 'http-parser/2.8.1@includeos/stable' package for the specified settings, options and dependencies:
- Settings: arch=x86, build_type=Release, compiler=clang, compiler.version=6.0, os=Linux
- Options: 
- Dependencies: 
- Package ID: 53bfe98e7c9ebae022aa252c74a10f09cc4898b0

ERROR: Missing prebuilt package for 'http-parser/2.8.1@includeos/stable'
Try to build it from sources with "--build http-parser"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"

There's a bunch of missing packages like http-parser and if I try to run conan with --build missing, it spits out some rather opaque errors like this while building botan:

error: unknown target triple 'x86-pc-linux-gnu', please use -triple or -arch
error: unknown target triple 'x86-pc-linux-gnu', please use -triple or -arch

**Comment by KristianJerpetjon** [comment]
Hi i suggest trying x86_64 x86 is only supported for platform nano
