### ISSUE TITLE
Booting Bare Metal

### ISSUE THREAD

**Issue by tweekley49** [includeos/IncludeOS#2178]
If I was wanting to boot this on a bare metal machine for testing security and performance (no network stack needed), how would you recommend going about it?

**Comment by fwsGonzo** [comment]
After building a machine image you will need to attach GRUB to it so that it can boot anywhere. I have a repo that used to do this: https://github.com/fwsGonzo/physboot But I haven't updated it in a while, so maybe all the scripts won't work, but the important thing is just to be able to call grub-mkrescue properly.

```
LOCAL_DISK=temp_disk
SERVICE=/path/to/service.elf

# create grub.iso
mkdir -p $LOCAL_DISK/boot/grub
cp $SERVICE $LOCAL_DISK/boot/service
cp grub.cfg $LOCAL_DISK/boot/grub
echo "=>"
grub-mkrescue -d /usr/lib/grub/i386-pc -o grub.iso $LOCAL_DISK
echo "grub.iso constructed"
```
Hope that helps! 👍

**Comment by tweekley49** [comment]
> 
> 
> After building a machine image you will need to attach GRUB to it so that it can boot anywhere. I have a repo that used to do this: https://github.com/fwsGonzo/physboot But I haven't updated it in a while, so maybe all the scripts won't work, but the important thing is just to be able to call grub-mkrescue properly.
> 
> ```
> LOCAL_DISK=temp_disk
> SERVICE=/path/to/service.elf
> 
> # create grub.iso
> mkdir -p $LOCAL_DISK/boot/grub
> cp $SERVICE $LOCAL_DISK/boot/service
> cp grub.cfg $LOCAL_DISK/boot/grub
> echo "=>"
> grub-mkrescue -d /usr/lib/grub/i386-pc -o grub.iso $LOCAL_DISK
> echo "grub.iso constructed"
> ```
> 
> Hope that helps! 👍

I am also having it write to my spare partition (sdb) but when I boot it in grub I get errors.
It's telling me:

"error: Not a regular file
 error: you need to load the kernel first"

Could I be pointing to the wrong elf file? (The only elf I get from building the service is .elf.bin)
Any thoughts?

Also, I wanted to thank you for your help that you have given me! I am doing research for one of my classes on this Unikernel and I have had a blast with it!

**Comment by fwsGonzo** [comment]
You won't have to modify grub.cfg, just make sure you are actually creating a grub.iso file, which might require `grub-pc-bin` and yes, it's probably going to be the elf.bin, as long as the `file` command says its an ELF file.

**Comment by tweekley49** [comment]
> 
> 
> You won't have to modify grub.cfg, just make sure you are actually creating a grub.iso file, which might require `grub-pc-bin` and yes, it's probably going to be the elf.bin, as long as the `file` command says its an ELF file.

The grub.iso is being created... I just get a black screen with "Grub" in the top left corner..Anything in specific I should look for on the .iso to make sure it is there?

**Comment by fwsGonzo** [comment]
oh right, you will want to add the VGA output driver, as there is no terminal anymore... unless you connect a serial port

`add_stdout(myservice vga_output)`

**Comment by tweekley49** [comment]
> oh right, you will want to add the VGA output driver, as there is no terminal anymore... unless you connect a serial port
> 
> `add_stdout(myservice vga_output)`

Just to verify, which file am I going to put that into? I'm not familiar with that command.

**Comment by fwsGonzo** [comment]
Add it to the bottom of your CMakeLists.txt, its not a normal command, its a function we made for IncludeOS that adds a stdout plugin. It's not well-documented at all. Yet :)

**Comment by tweekley49** [comment]
> Add it to the bottom of your CMakeLists.txt, its not a normal command, its a function we made for IncludeOS that adds a stdout plugin. It's not well-documented at all. Yet :)

Awesome! Will run it soon and let you know if that fixes my issue! 

Again, thank you for all your help!

**Comment by tweekley49** [comment]
Worked like a charm, thank you!

**Comment by am11** [comment]
> ```
> LOCAL_DISK=temp_disk
> SERVICE=/path/to/service.elf
> 
> # create grub.iso
> mkdir -p $LOCAL_DISK/boot/grub
> cp $SERVICE $LOCAL_DISK/boot/service
> cp grub.cfg $LOCAL_DISK/boot/grub
> echo "=>"
> grub-mkrescue -d /usr/lib/grub/i386-pc -o grub.iso $LOCAL_DISK
> echo "grub.iso constructed"
> ```

Thanks. I build hello_world image by modifying the last line https://github.com/includeos/hello_world/blob/5b95d9a79acde3e2396c25a173dbe1bb39f379d4/CMakeLists.txt#L10 to: `os_add_stdout(hello vga_output default_stdout)`. When I tested the generated `grub.iso` from the script with qemu: `qemu-system-x86_64 -boot d -cdrom grub.iso -m 512 -nographic`, it fails to boot the OS/application and opens grub prompt.

same thing happened when tested by flashing the ISO to an SD card and tried booting from device via qmeu from Windows:

```powershell
#!/usr/bin/env pwsh
C:\> Get-WmiObject Win32_DiskDrive | Where Caption -eq 'SDHC Card'

Partitions : 2
DeviceID   : \\.\PHYSICALDRIVE1
Model      : SDHC Card
Size       : 30951728640
Caption    : SDHC Card

$ &"\Program Files\qemu\qemu-system-x86_64.exe" -L "\Program Files\qemu" `
     -drive file=\\.\PhysicalDrive1,format=raw,media=disk -m 512 --no-reboot
```

![image](https://user-images.githubusercontent.com/3840695/111482832-eeda3f00-873c-11eb-9e02-de603c886d17.png)
followed by 
![image](https://user-images.githubusercontent.com/3840695/111483017-15987580-873d-11eb-846a-ecbce45c7017.png)

I ultimately wanted to test it on a physical machine with legacy BIOS option. Is there anything missing?

**Comment by fwsGonzo** [comment]
I did create some bootable images for my own computer from this repo: https://github.com/fwsGonzo/physboot
Maybe it can still work for you.

**Comment by am11** [comment]
Ops, I was missing grub.cfg. Used this one to make it work: https://github.com/includeos/IncludeOS/blob/99b60c782161f521edd797f789c35158109d9d44/test/kernel/integration/grub/grub.cfg#L1
