### ISSUE TITLE
Question: WIndows examples

### ISSUE THREAD

**Issue by MythreyaK** [includeos/IncludeOS#2182]
I was wondering how to get started with IncludeOS on windows. From what I've read so far, this doesn't seem to be a supported scenario.

**Comment by fwsGonzo** [comment]
Sadly, that isn't so easy to do. You will need a POSIX-like environment just to build the OS, and the services, and then you will still need a hypervisor to run the OS inside. I recommend just using Ubuntu for IncludeOS development.

**Comment by MythreyaK** [comment]
Okay! I have a few more questions if that's okay. 

I've seen some issues on WSL (v1 or v2, not sure). Is using IncludeOS under that environment supported? 

Thanks for the info!

**Comment by fwsGonzo** [comment]
I would think that you can easily build IncludeOS in WSL, however WSL doesn't support network bridges, so if you want to use networking (and assuming that Qemu works in WSL, which it might), then you will have to make sure to change the network backend from bridge to "user networking" (SLIRP) in our vm.json files.

Right now our network configuration is upside-down, as bridge is the default. Bridge is high-performant and works out of the box on Linux, but it's not so simple on the other platforms. It also doesn't give you internet access unless you add the routes yourself. It's just like a new network interface. User networking is slow, and emulated, but gives you internet access and works everywhere. At least, I think it does.

Take a look at https://github.com/includeos/demo-examples/tree/master/http_client - specifically vm.json, which uses the "user" backend.

**Comment by MythreyaK** [comment]
Thank you! I'm still getting the hang of it, so I'll close the issue for now.
