### ISSUE TITLE
Question: Is IncludeOS still under active development?

### ISSUE THREAD

**Issue by bodgergely** [includeos/IncludeOS#2183]
I am wondering as I have not seen much activity related to IncudeOS netiher on github nor on includeos's tech blog.

**Comment by fwsGonzo** [comment]
Sorry, but no. There are things happening here and there, for example pthreads just got merged, but otherwise development is very slow. There are plans to run on RPI4 soon (TM), if that's of any interest, otherwise the general development is low-frequent.

**Comment by bodgergely** [comment]
@fwsGonzo Thanks for getting back.
