### ISSUE TITLE
Building with PThreads

### ISSUE THREAD

**Issue by tweekley49** [includeos/IncludeOS#2198]
Looking to build an application that utilizes PThreads, however, it doesn't build. The error below is generated, it seems to be an issue with conan code that includeOS is using to build from?? Any idea to this fix?

/.conan/data/musl/1.1.18/includeos/stable/build/b6ca6a0ffff110bf17b843d4258482a94281eb43/musl/src/thread/pthread_create.c:301: undefined reference to `syscall_SYS_sched_setscheduler'

Thanks!

**Comment by fwsGonzo** [comment]
Not sure why you're getting that. The function exists in the latest version of the OS. Also, if you want pthreads I recommend using the latest master and not an old version of the OS.

Make the OS editable, then build services from that. It should work.

**Comment by tweekley49** [comment]
Still no luck. I pulled down the latest master and built it but none of the versions got updated. Maybe I am doing something wrong....not quite sure. Could it be issue that the program I am using is in C and not C++??
The error is still the same above so maybe I did not update it like I thought I did...

**Comment by fwsGonzo** [comment]
Hey, have you made the OS editable? If so, then you should try adding this to the conanfile.py in the root folder and then re-initializing the build folder completely:
```
            self.requires("musl/1.1.24@includeos/latest")
```
Just place it with the other dependencies, maybe between libcxx and libgcc, line 40.

Once you have built the OS with the new dependency, then you need to update the build folder for your service as well. It should build now, and you should have threads with parallellism. Hope this helps.

**Comment by tweekley49** [comment]
That did the trick. Now it is saying there is undefined reference to
syscall_SYS_clock_nanosleep in musl 1.1.24 :/

**Comment by fwsGonzo** [comment]
That's because the OS is not in editable mode, maybe. I don't really know how to perfectly get it working. Have you used `conan editable ..`?

**Comment by tweekley49** [comment]
I believe it is in editable mode. Following what you gave me, I was able to update musl from 1.1.18 to 1.1.24 and that is what it said it build with. I put it in editable mode following the steps in the wiki / built it after adding musl 1.1.24 as a dependency and have just left it in editable mode

**Comment by tweekley49** [comment]
Here were my steps. I believe the issue is that musl 1.1.24 got "installed" somewhere completely random / doesn't exist.

inside IncludeOS dir I made a build folder, in /etc/layout.txt I didn't change anything since build_dir was already pointing to build. Then I did:
 `$ conan editable add . includeos/$(conan inspect -a version . | cut -d " " -f 2)@includeos/latest --layout=etc/layout.txt`
Then I did conan editable list to verify and the output was good. Then I ran...
`$ cd includeos
$ conan install -if build . -pr clang-6.0-linux-x86_64
$ conan build -bf build .`

That was where I stopped...any mistakes in what I did?

**Comment by fwsGonzo** [comment]
I don't see you building the OS anywhere. Try this instead:

Go into the IncludeOS folder.
```
mkdir -p build
cd build
conan install .. -pr clang-6.0-linux-x86_64
source activate.sh
cmake ..
make -j4
```
That should build the OS itself, and it should be automatically picked up by any services you build now.

**Comment by tweekley49** [comment]
This seems to be the issue...
![image](https://user-images.githubusercontent.com/16714618/74556231-95955000-4f2b-11ea-9de0-66e964c5aecb.png)

/home/gonzo isn't a thing on my pc, so I'm not quite sure it is checking there?

**Comment by fwsGonzo** [comment]
It's not using your editable OS built from source. Try changing your editable from <whatever> to version 9.9.9?
You can see what you currently use with `conan editable list`.

**Comment by tweekley49** [comment]
I must be changing the wrong thing...my 'conan editable list' is:
'includeos/0.15.1-119@includeos/latest
       Path: /home/tyler/includeos
       Layout: /home/tyler/includeos/etc/layout.txt`

I am still getting the same error?? I must not be setting the editable version correctly to be used?

**Comment by fwsGonzo** [comment]
It looks OK to me. I think you are just seeing paths from the PC that build the package originally, but it just looks to me like it's not picking up your editable OS built from source.

The editable list you posted looks OK. Have you initialized the build folder again after fixing the editable?

**Comment by tweekley49** [comment]
I have, but to make sure I am doing it correctly I am doing this...
I made the OS editable, did everything you said above, rebuild it with the commands above and then i try to apply it to my project I am trying to build so I:
cd back to home and do this....
'mkdir -p radix && cd radix'  (then i paste my .c file in there with the CMakeLists.txt and conanfile.txt)
'mkdir -p build && cd build'
'conan install .. -pr clang-6.0-linux-x86_64'
'source activate'
'cmake ..'
'cmake --build .'
and this produces : 
![image](https://user-images.githubusercontent.com/16714618/74564028-13615780-4f3c-11ea-9eb5-2fc293f26bc7.png)

**Comment by fwsGonzo** [comment]
Don't pay too much attention to musl here. It's working. You need to get the OS editable.

The thing about nanosleep is that it's implemented in the OS, so it can't be anything wrong with the musl package. It just confirms that it works. It also confirms that the OS is not being activated as an editable, and I don't know why.

So, what to try here? Have  you tried editing the editable and increasing the version number? 9.9.9 would make your version higher than the package.

**Comment by tweekley49** [comment]
Where would I edit the editable's version number? I am looking inside of conanfile.py currently

**Comment by fwsGonzo** [comment]
The problem is... me :) You need to checkout one of my branches. My bad. It's not master, master is old and irrelevant.

Do this:
```
git remote add gonzo git@github.com:fwsGonzo/IncludeOS.git
git fetch gonzo
git checkout -b simpler_clone gonzo/simpler_clone
```

Now, go into the build folder, build the OS, and then simply build your service.

Sorry for the confusion. I don't think about these things.

**Comment by tweekley49** [comment]
Running into an issue now where it is saying there is multiple declarations LOL
I am troubleshooting the issue now, but anything come to mind off the top of your head?

**Comment by fwsGonzo** [comment]
Can you post the errors you are getting?

**Comment by tweekley49** [comment]
![image](https://user-images.githubusercontent.com/16714618/74580000-7cad8e80-4f6d-11ea-86f0-d685deab98e6.png)
I checked out your smp branch and then rebuilt the OS and rebuilt my service and I get that error

**Comment by fwsGonzo** [comment]
Did you try building musl manually with --build? It looks like it still has __clone which is not the right package.

You can build musl with `conan install .. -pr clang-6.0-linux-x86_64 --build musl`

**Comment by tweekley49** [comment]
Worked like a charm! Thank you for all your help during that! That was awesome stuff getting to plug and play until it was working. Again, thank you for all your help!!

**Comment by fwsGonzo** [comment]
No problem. If you want to use SMP (multiprocessing) then there's a work-around for it.
Go into src/musl/futex.cpp and change to this:
```
			while (*uaddr == val) asm("pause"); // __thread_yield();
```
It will make cooperative threads stop working, but it will make multi-processing stable.
