### ISSUE TITLE
Possible data race in src/posix/pthread.cpp

### ISSUE THREAD

**Issue by mfbalin** [includeos/IncludeOS#2200]
Inside pthread_create, static int __thread_id__ = 0 increments each time a new thread is created, and it is not atomic, possibly causing a data race.

**Comment by fwsGonzo** [comment]
Not saying you are wrong here because there IS a race inside my threads implementation, but are you sure about this? Because I'm incrementing using:
```
  inline long generate_new_thread_id() noexcept {
	  return __sync_fetch_and_add(&thread_counter, 1);
  }
```

**Comment by mfbalin** [comment]
```auto new_id = __thread_id__++;```
This is what I see on line 16.

**Comment by fwsGonzo** [comment]
Oh yes, I thought you meant src/kernel/threads.cpp. No, we don't use that anymore - it should have been deleted. We get pthreads from musl now.

**Comment by mfbalin** [comment]
Alright, thanks. I was glancing over the code and thought maybe I should open an issue about this.
