### ISSUE TITLE
Writing grub.iso to external hard drive

### ISSUE THREAD

**Issue by tweekley49** [includeos/IncludeOS#2201]
Completely stumped....on my VM, I can add a new hard drive and DD to it and boot the unikernel on sdb no problem. If I try to DD and boot from usb onto the laptop, it doesn't work and all I get is a gray screen... Any idea why that might be? Doing the same exact commands to the VM vmdk and the USB... I have secure boot off as well.

**Comment by fwsGonzo** [comment]
does the laptop use secure boot or EFI/UEFI? you would have to disable that

**Comment by tweekley49** [comment]
I switched to legacy mode.

**Comment by fwsGonzo** [comment]
Do you get the GRUB menu? if not thats not something I can help with
otherwise, when you boot on real hardware you need the VGA stdout driver, otherwise you have no way to see whats going on
Qemu prints serial output in the terminal, which a real computer won't do, obviously
but you can connect a serial port to your motherboard and use a second computer to read the serial port output.

**Comment by tweekley49** [comment]
Yes. So what I did to ensure that was removed pointing to my kernel in grub.cfg and as expected, it failed, and gave me the grub menu. So when I edit the grub.cfg again from the grub menu and tell it to boot, I get the grey blinking screen. To me that indicates something is wrong with add_stdout(vga_output).

But here is the confusing thing - when I did a fresh build of IncludeOS it worked. 

When I did a clone, added your smp branch, and built it / put it in editable mode - vga_output no longer worked. As described above, I could get to grub menu on boot but when I would point to kernel and run it - grey screen. No crashes, nothing, so it was running the kernel but not outputting it in vga like I specified to do in CMake file.

**Comment by fwsGonzo** [comment]
That's very strange - it really should print *something* as there is nothing changed in the startup of the OS. I would have to investigate that further to find out what's going on. I don't have a setup for running on bare metal right now, but I might try something later just to see that it boots properly.

**Comment by tweekley49** [comment]
Yeah - nothing will print when I am working off the latest IncludeOS in editable mode. Everything has been built, but I don't get VGA output.

**Comment by fwsGonzo** [comment]
The next best thing to do would be to try to run on more hypervisors with VGA enabled, with GRUB as the loader.

**Comment by tweekley49** [comment]
> The next best thing to do would be to try to run on more hypervisors with VGA enabled, with GRUB as the loader.

I am doing a serial to USB using Minicom with a 38400 8N1 and the output doesn't get displayed properly. Is there a tool you would recommend?? The characters are coming through but the formatting makes it unreadable.

**Comment by fwsGonzo** [comment]
I think you can configure the minicom to display it correctly. We have done it before, but I can't remember any of the details - maybe @KristianJerpetjon has some insight.

**Comment by tweekley49** [comment]
> I think you can configure the minicom to display it correctly. We have done it before, but I can't remember any of the details - maybe @KristianJerpetjon has some insight.

Hopefully! Messing around with configurations - but just can't seem to get the display settings right, sadly.
